# Generated by Django 5.2.5 on 2025-12-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duzenleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('resmi_gazete', 'Resmî Gazete'), ('gib', 'Gelir İdaresi Başkanlığı')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('publish_date', models.DateField()),
                ('url', models.URLField(blank=True, null=True)),
                ('raw_text', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('sectors', models.JSONField(blank=True, default=list)),
                ('impact_type', models.CharField(blank=True, choices=[('zorunlu', 'Zorunlu'), ('opsiyonel_tesvik', 'Opsiyonel Teşvik'), ('risk', 'Dikkat / Risk')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sirket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(choices=[('yazilim', 'Yazılım'), ('imalat', 'İmalat'), ('perakende', 'Perakende'), ('lojistik', 'Lojistik')], max_length=50)),
                ('employee_count', models.PositiveIntegerField()),
                ('location_city', models.CharField(max_length=100)),
                ('is_exporter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
