# Generated by Django 5.2.5 on 2025-12-10 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mevzuat_parca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SirketObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_applicable', models.BooleanField(default=True)),
                ('is_compliant', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duzenleme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mevzuat_parca.duzenleme')),
                ('sirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mevzuat_parca.sirket')),
            ],
        ),
    ]
