# Generated by Django 5.2.5 on 2025-12-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mevzuat_parca', '0002_sirketobligation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirket',
            name='unvan',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
