# Generated by Django 5.2.5 on 2025-12-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mevzuat_parca', '0003_sirket_unvan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sirket',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='sirket',
            name='vkn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='employee_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='location_city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='sector',
            field=models.CharField(blank=True, choices=[('yazilim', 'Yazılım'), ('imalat', 'İmalat'), ('perakende', 'Perakende'), ('lojistik', 'Lojistik')], db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='unvan',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
